name: CI / CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: test  # This ensures that the deploy job runs only after the test job has completed successfully
    environment: production
    env:
      VPS_HOST: ${{ vars.VPS_HOST }}
      VPS_PROJECT_PATH: ${{ vars.VPS_PROJECT_PATH }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_SSH_USER: ${{ vars.VPS_SSH_USER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create Privare Key
        run: |
          echo "$VPS_SSH_KEY" > private_key
          chmod 600 private_key

      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
          
      - name: Upload the current directory to VPS
        run: |
          scp -i private_key -o StrictHostKeyChecking=no -r ./* $VPS_SSH_USER@$VPS_HOST:$VPS_PROJECT_PATH
