name: CI / CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: test  # This ensures that the deploy job runs only after the test job has completed successfully
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy to VPS
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

        run: |
          echo "$VPS_SSH_KEY" > private_key
          chmod 600 private_key

          # Add the host key to known_hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
          
          scp -i private_key -o StrictHostKeyChecking=no -r ./* $VPS_SSH_USER@$VPS_HOST:$VPS_PROJECT_PATH
